name: Monthly History Cleanup
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: 

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete all workflow runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # We add the --repo flag so the CLI knows exactly where to look
          gh run list --repo ${{ github.repository }} --order asc --limit 1000 --json databaseId -q '.[].databaseId' | xargs -I{} gh run delete --repo ${{ github.repository }} {}
